version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express

  express:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    volumes:
      - ./mariadb:/var/lib/mysql
