version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    volumes:
      - ./mariadb:/var/lib/mysql
